print("Buenas tardes, bienvenido a tu carrito de compras!! ")
shopping_list = []
articulo_1 = input("Agregue el primer elemento: ")
articulo_2 = input("Agregue el segundo elemento: ")
articulo_3 = input("Agregue el tercer elemento: ")
print(shopping_list)
print("Elementos agregados al carrrito: ")
shopping_list.append(articulo_1)
shopping_list.append(articulo_2)
shopping_list.append(articulo_3)
print(shopping_list) 